# Fail-on-base evidence: the head's tests run against the base's production code.
EVIDENCE = {
"01": ("server/src/__tests__/tool-gateway.test.ts", "managed initialize and notifications get `401` with \"Agent token did not verify\" instead of the empty gateway response, in both deployment modes."),
"02": ("server/src/__tests__/agent-auth-middleware.test.ts, server/src/__tests__/tool-gateway.test.ts", "a `pcgt_` bearer gets `401` instead of `200`, and bad session bearers get the middleware error instead of the gateway reason codes (`session_revoked`, `session_run_inactive`)."),
"02b": ("server/src/__tests__/tool-gateway.test.ts", "a named gateway token on the session routes gets `200` instead of `401`."),
"03": ("adapter-utils, claude-local, codex-local, cursor-cloud, CLI and server tests", "The adapter environment, the sandbox bridges, the Codex MCP config, the Claude and Codex allowlists, the CLI, server boot, and the Cloud claim do not expose or use `PAPERCLIP_RUNTIME_API_URL` (for example `expected undefined to be 'http://10.0.0.5:3100'`)."),
"04": ("server/src/__tests__/remote-mcp-timeout-health.test.ts", "after a timeout the connection health is `error` instead of `degraded`, the tools disappear, and the audit has no `failureKind`."),
"04b": ("server/src/__tests__/remote-mcp-timeout-health.test.ts", "(Base: pull request 04.) the timed-out write is returned as `replayed` instead of `409`."),
"05": ("server/src/__tests__/http-log-redaction.test.ts", "sentinel tokens appear in the request headers, the response headers, unlisted credential headers, string fields, and the `401` log, and a logged error with a throwing property aborts the log call."),
"06": ("server/src/__tests__/issue-execution-policy.test.ts, server/src/__tests__/issue-execution-policy-routes.test.ts", "the approval returns `422` instead of `200`, and the transitions select no participant."),
"07": ("server/src/__tests__/heartbeat-review-handoff-retry.test.ts (the new retry module kept, the route and recovery-service wiring of master)", "no handoff is enqueued after the blocker clears or the environment lease is released (`0` instead of `1`), and no escalation is created after the last attempt."),
"08": ("server/src/__tests__/workspace-validation-recovery-precedence.test.ts, server/src/services/recovery/stranded-notice.test.ts", "the cause becomes `stranded_assigned_issue` or `execution_review_participant_recovery` instead of `workspace_validation_failed`, and a wrapped failure is recorded as `adapter_failed`."),
"11": ("server/src/services/native-runtime/native-runner-file-handoff.test.ts", "registration fails with `ENOENT` for the escaped path, and the invalid escape run fails with `ENOENT` instead of the descriptor error."),
"12": ("server/src/__tests__/workspace-runtime-start-terminality.test.ts", "the port reservation survives `resetRuntimeServicesForTests()`."),
"14": ("server/src/__tests__/tool-gateway.test.ts", "(Base: pull request 16.) the tools are listed under the old `mcp.<app>-<connection>:<tool>` names."),
"15": ("server/src/__tests__/tool-gateway.test.ts", "`initialize` advertises resources and prompts to a token that allows neither."),
"16": ("server/src/__tests__/tool-gateway.test.ts", "a `tool_name` entry with the catalog name matches no tool at the gateway, and the stored gateway-name entries stay unconverted."),
"19": ("server/src/__tests__/issue-execution-policy-routes.test.ts", "the route cancels the calling agent's own run."),
"20": ("server/src/__tests__/conversation-continuation.test.ts", "the lost run of the declaring adapter is not stamped for continuation (`stopReason: process_lost`). The control test passes on both."),
"21": ("server/src/__tests__/shutdown-waits-for-adapter-run-stops.test.ts, server/src/shutdown.test.ts", "the config has no drain timeout, a wakeup after shutdown begins starts the run instead of leaving it queued, and the timeout is not logged as an error with the run IDs."),
"22": ("server/src/__tests__/release-cancelled-interrupted-run-leases.test.ts", "the lease stays `active` after each path."),
"22b": ("server/src/__tests__/release-cancelled-interrupted-run-leases.test.ts", "(Base: pull request 22.) the lease of a run with a live child is released (`expired`, `pending_cleanup`) instead of staying `active`."),
"23": ("server/src/__tests__/scope-named-gateway-tool-discovery.test.ts", "discovery evaluates the other connections' tools, and `namedGatewayDiscoveryScope` does not exist. The allow-policy guard test passes on both."),
"23b": ("server/src/__tests__/tool-policy-read-cache.test.ts", "189 selects for 20 tools against 69 for 5 tools."),
"24": ("server/src/__tests__/run-gateway-token-lifetime.test.ts, server/src/__tests__/heartbeat-runtime-mcp-servers.test.ts", "the run tokens are stored with a one-hour expiry, and the running run's token is rejected with `gateway_token_expired` after two hours."),
"25": ("server/src/__tests__/remote-mcp-socks-proxy.test.ts", "the proxy is ignored, so requests (also the OAuth sign-in) dial the target directly, and invalid or private proxies and oversized hostnames are accepted."),
"26": ("server/src/__tests__/issue-runless-agent-key-routes.test.ts", "`403` \"Cross-issue writes need a run\" and `401` \"Agent run id required\" for the runless update, the inline comment, and the held-issue cases."),
"27a": ("server/src/__tests__/heartbeat-run-status-transition-authority.test.ts", "The source scan finds 33 status writes outside the authority. Restoring the base version of the native session executor alone makes it flag that file's hidden writes."),
"27b": ("packages/db/src/post-commit-hooks.test.ts", "`registerPostCommitHook` does not exist on the base. This is a new primitive, so no base behavior can fail for a different reason."),
"27c": ("server/src/__tests__/lifecycle-events.test.ts", "(Base: the merge of 27a and 27b.) no record is logged. The rollback and same-status tests pass on both."),
"27d": ("server/src/__tests__/heartbeat-run-cancellation-attribution.test.ts", "(Base: pull request 27c.) the cancellation record has no `cancellation` object."),
"28": ("packages/adapter-utils/src/server-utils.test.ts", "The owning run gets no `EPIPE` result, and the write raises an unhandled `EPIPE` error in the test process."),
}
